{#- OZI 0.1
# ozi/templates/coverage.pyproject.toml
# SPDX-License-Identifier: Unlicense
-#}
[tool.coverage.report]
exclude_lines = [
    "{{ spec.python.src.comments.pragma_no_cover }}",
    "{{ spec.python.src.comments.pragma_defer_to }}",
    "def __repr__",
    "def __wrapper", # functools.wraps decorated functions
    "(\\.\\.\\.)",
    "@(abc\\.)?abstractmethod",
    "class .*\\bProtocol\\):",
    "if __name__ == .__main__.:",
    ]
fail_under    = {{ spec.python.src.format.min_coverage }}
show_missing  = true
skip_covered  = true
skip_empty    = true

[tool.coverage.run]
branch         = true
relative_files = true
